#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF
usage: git commit-subject-stats [<options>] [--] [<shortlog args>]

For each user in the output of shortlog, print:
    (1) number of commits
    (2) number of commits with subjects longer than 50 chars
    (3) average commit subject length
    (4) ratio of (2) to (1)
    (5) name

Options:
    -h, --help          show this help message and exit
EOF
}

while (( $# )); do
  case "$1" in
    -h|--help)
      usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
  shift
done

git shortlog "$@" | awk '
/^[^ ]/ {
  sub(/ \([0-9]+\):$/, "");
  name = $0;
}
/^[ ]/ {
  ++commits;
  chars += length($0) - 6;
  long += length($0) > 56;
}
/^$/ {
  printf "%d\t%d\t%.3f\t%.3f\t%s\n", commits, long, chars / commits, long / commits, name;
  commits = 0;
  chars = 0;
  long = 0;
}' | less -FRX
