#!/usr/bin/env bash

usage() {
  cat <<EOF
usage: git collisions [<options>] [--] [<rev-list args>]

Print commit hash collisions.

If no <rev-list args> are specified, default to "--all".

Options:
    -d, --digits        number of leading digits; default core.abbrev or 7
    -h, --help          show this help message and exit
EOF
}

digits=

while (( $# )); do
  case "$1" in
    -d|--digits)
      shift
      digits="$1"
      ;;
    -h|--help)
      usage
      exit
      ;;
    --)
      shift
      break
      ;;
    *)
      break
      ;;
  esac
  shift
done

[[ -n "$digits" ]] || digits="$(git config core.abbrev)" || digits="7"

git rev-list ${@:---all} | sort \
  | uniq --check-chars="$digits" --all-repeated \
  | uniq --check-chars="$digits" --group \
  | less -FRX
